### ISSUE TITLE
Consider giving HighlightRange a priority to resolve the styling of overlapping ranges

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [dlibby-/highlight#2]
If find on page and spellcheck both have a range applied over the same content, they should compose into a combined style.  If they specify conflicting styling (e.g. both have a background-color) then we should allow one to take priority over the other.  The cascade can't solve this on its own because the two overlapping ranges can belong to different groups.

**Comment by dlibby-** [comment]
This should be addressed in the latest explainer pushed to master (I should start doing PRs and referencing issues, sorry)
